version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: familynest-postgres
    environment:
      POSTGRES_DB: familynest
      POSTGRES_USER: familynest
      POSTGRES_PASSWORD: familynest123
    ports:
      - "5433:5432"  # Use 5433 to avoid conflict with local PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - familynest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U familynest -d familynest"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: familynest-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"  # Use 8081 to avoid conflict with local backend
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - familynest-network

volumes:
  postgres_data:
  backend_uploads:

networks:
  familynest-network:
    driver: bridge 