version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: familynest-postgres
    environment:
      POSTGRES_DB: familynest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialize with fresh schema only (no test data)
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d:ro
    networks:
      - familynest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d familynest_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: familynest-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/familynest_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - familynest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
  backend_uploads:

networks:
  familynest-network:
    driver: bridge 